-   name: Create app a directory
    file:
        path: "{{app_directory_prefix}}/"
        state: directory
        mode: '0755'

-   name: generate docker-compose config
    template:
        src: "docker-compose.yml.j2"
        dest: "{{app_directory_prefix}}/docker-compose.yml"
        mode: 0644

-   name: generate nginx config
    template:
        src: "nginx.conf.j2"
        dest: "{{app_directory_prefix}}/nginx.conf"
        mode: 0644

-   name: Stop all services
    community.docker.docker_compose:
        project_src: "{{app_directory_prefix}}"
        stopped: yes

-   name: Create and start services
    community.docker.docker_compose:
        project_src: "{{app_directory_prefix}}"
    register: output